from django.urls import path
from django.contrib.sitemaps.views import sitemap as sitemap_view
from . import admin, views, sitemap

urlpatterns = [
    path("admin/", admin.index),
    path("admin/sign-in/", admin.sign_in),
    path("admin/sign-out/", admin.sign_out),
    path("admin/change-password/", admin.change_password),
    path("admin/change-email/", admin.change_email),
    path("admin/change-username/", admin.change_username),
    path("admin/ping/", admin.ping),
    path("admin/files/", admin.FileSystem.list_directory),
    path("admin/new-directory/", admin.FileSystem.new_directory),
    path("admin/upload-files/", admin.FileSystem.upload),
    path("admin/delete-files/", admin.FileSystem.delete),
    path("admin/rename/", admin.FileSystem.rename),
    path("articles/", views.articles),
    path("download/", views.download),
    path("preview/", views.preview),
    path("admin/copy-files/", admin.FileSystem.copy),
    path("admin/move-files/", admin.FileSystem.move),
    path("admin/search-files/", admin.FileSystem.search),
    path("admin/save-article/", admin.save_article),
    path("load-article/", views.load_article),
    path("admin/delete-article/", admin.delete_article),
    path("admin/change-description/", admin.change_description),
    path("admin/change-full-name/", admin.change_full_name),
    path("admin/change-profile-picture/", admin.change_profile_picture),
    path("admin/remove-profile-picture/", admin.remove_profile_picture),
    path("profile-picture/", views.profile_picture),
    path("admin/admins/", admin.admins),
    path("admin/find-admin/", admin.find_admin),
    path("admin/create-admin/", admin.create_admin),
    path("admin/delete-admin/", admin.delete_admin),
    path("admin/send-verification-code/", admin.send_verification_code),
    path("admin/verify", admin.verify),
    path("admin/reset-password", admin.reset_password),
    path("admin/tags/", admin.tags),
    path("admin/categories/", admin.categories),
    path("admin/delete-tag/", admin.delete_tag),
    path("admin/delete-category/", admin.delete_category),
    path("admin/edit-tag/", admin.edit_tag),
    path("admin/edit-category/", admin.edit_category),
    path("admin/create-tag/", admin.create_tag),
    path("admin/create-category/", admin.create_category),
    path("admin/mail/", admin.mail),
    path("admin/load-mail/", admin.load_mail),
    path("admin/load-particular-mail/", admin.load_particular_mail),
    path("admin/delete-mail/", admin.delete_mail),
    path("events/", views.events),
    path("gallery/", views.gallery),
    path("load-event/", views.load_event),
    path("load-gallery-image/", views.load_gallery_image),
    path("admin/save-gallery-image/", admin.save_gallery_image),
    path("admin/delete-gallery-image/", admin.delete_gallery_image),
    path("admin/save-event/", admin.save_event),
    path("admin/delete-event/", admin.delete_event),
    path("sitemap.xml", sitemap_view, {"sitemaps": {"blog": sitemap.BlogEngineAppSitemap}})
]
