# Generated by Django 2.0.6 on 2019-02-28 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('hash', models.CharField(default='DgzmJyjl2isWkjH1yFq0', max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('last_active', models.DateTimeField(auto_now_add=True)),
                ('current_activity', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=300, null=True)),
                ('profile_picture', models.FileField(null=True, upload_to='profile-pictures')),
                ('immunity', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('hash', models.CharField(default='PIS7f82pM41ep8EM3M7b', max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('body', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('cover_photo', models.CharField(max_length=100, null=True)),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogEngineApp.Admin')),
            ],
            options={
                'ordering': ['-published_on'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogEngineApp.Article')),
                ('reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BlogEngineApp.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='FileLikeObject',
            fields=[
                ('hash', models.CharField(default='h4hhcSRI7zFrM5KLyp5X', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=50)),
                ('file', models.FileField(null=True, upload_to='files')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogEngineApp.FileLikeObject')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogEngineApp.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BlogEngineApp.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='BlogEngineApp.Tag'),
        ),
    ]
