# Generated by Django 2.0.6 on 2019-02-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEngineApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='hash',
            field=models.CharField(default='3W87nkq8CjhnP2Qo6707', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='hash',
            field=models.CharField(default='p1St7WE6Wiu6de3JH4GI', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filelikeobject',
            name='hash',
            field=models.CharField(default='tvZe4B1xz11fEs80FUfr', max_length=20, primary_key=True, serialize=False),
        ),
    ]
