# Generated by Django 2.0.6 on 2019-03-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEngineApp', '0002_auto_20190228_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='admin',
            name='hash',
            field=models.CharField(default='s1wH5J7FQj8CZ66fy19s', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='hash',
            field=models.CharField(default='pi3Expg892WR8ab3FIZI', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filelikeobject',
            name='hash',
            field=models.CharField(default='97x3lXypH044Emy44y94', max_length=20, primary_key=True, serialize=False),
        ),
    ]
