# Generated by Django 2.0.6 on 2019-03-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEngineApp', '0003_auto_20190303_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000)),
                ('editor_content', models.TextField()),
                ('raw_content', models.TextField()),
                ('is_draft', models.BooleanField()),
                ('sent_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='hash',
            field=models.CharField(default='82C1Fw3DM4x0F48G4QrI', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='hash',
            field=models.CharField(default='Vy1kOttg72RNLN1Tl1mb', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filelikeobject',
            name='hash',
            field=models.CharField(default='kK49M1649Rv44ql0WEvr', max_length=20, primary_key=True, serialize=False),
        ),
    ]
