# Generated by Django 2.0.6 on 2019-03-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEngineApp', '0004_auto_20190308_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='hash',
            field=models.CharField(default='9g8H3uaMTZ1z23mEj9J3', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='hash',
            field=models.CharField(default='c6w9aZD2vvJdE1yyr9mE', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filelikeobject',
            name='hash',
            field=models.CharField(default='L2rDyYJYM8EAlfXXAmdJ', max_length=20, primary_key=True, serialize=False),
        ),
    ]
