# Generated by Django 2.0.6 on 2019-03-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEngineApp', '0005_auto_20190308_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000)),
                ('editor_content', models.TextField()),
                ('raw_content', models.TextField()),
                ('is_draft', models.BooleanField(default=True)),
                ('sent_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.AlterField(
            model_name='admin',
            name='hash',
            field=models.CharField(default='9c65mR8WT86P66wz8uN8', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='hash',
            field=models.CharField(default='B3KJ75Cuyt9p8xToHOfQ', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filelikeobject',
            name='hash',
            field=models.CharField(default='5uZe5Ox505ERIN8x2CHE', max_length=20, primary_key=True, serialize=False),
        ),
    ]
