# Generated by Django 2.0.6 on 2019-03-09 13:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEngineApp', '0006_auto_20190309_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BlogEngineApp.Admin'),
        ),
        migrations.AddField(
            model_name='mail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='hash',
            field=models.CharField(default='u34f379crPc9I3Y3F4kY', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='hash',
            field=models.CharField(default='48k43NV8cMDl794Trqt8', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filelikeobject',
            name='hash',
            field=models.CharField(default='W6htgyfL47DN25uk97tP', max_length=20, primary_key=True, serialize=False),
        ),
    ]
