# Generated by Django 2.0.6 on 2019-03-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEngineApp', '0007_auto_20190309_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='hash',
            field=models.CharField(default='ObdOOZO5grh5aXJus5l0', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='hash',
            field=models.CharField(default='1lLWe1W7fY358nvD73l1', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filelikeobject',
            name='hash',
            field=models.CharField(default='2HAIoTd8Iz68c1X1rXjw', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visitorcount',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
