# Generated by Django 2.0.6 on 2019-03-25 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEngineApp', '0008_auto_20190311_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='raw_body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='hash',
            field=models.CharField(default='JnNUK9W9Uq7K85hQHQXJ', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='hash',
            field=models.CharField(default='Ps9gdbrK8M8n9ALBNon4', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filelikeobject',
            name='hash',
            field=models.CharField(default='LtTxq17nIv547F5KQMSP', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BlogEngineApp.FileLikeObject'),
        ),
    ]
