# Generated by Django 2.0.6 on 2019-03-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEngineApp', '0009_auto_20190325_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='admin',
            name='hash',
            field=models.CharField(default='j7iYSooi636oCNHX3o78', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='hash',
            field=models.CharField(default='v0Gq4v8QVDNYky2484CL', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filelikeobject',
            name='hash',
            field=models.CharField(default='ZrI25VE6cYM1YB28UTVf', max_length=20, primary_key=True, serialize=False),
        ),
    ]
