# Generated by Django 2.0.6 on 2019-03-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEngineApp', '0010_auto_20190327_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='admin',
            name='hash',
            field=models.CharField(default='8J2skNfHeUBkrmuNF493', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='hash',
            field=models.CharField(default='x12pvm251MKA586P41O6', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filelikeobject',
            name='hash',
            field=models.CharField(default='azhiW5fo4qti2pQryS5Y', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
